version: '3.9'
services:
  web:
    container_name: docker-compose-crud-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5000'
    volumes:
      - "docker-compose-crud-web-data:/app"
    depends_on:
      - db
    networks:
      - docker-compose-crud-network
  db:
    container_name: docker-compose-crud-db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - "docker-compose-crud-db-data:/var/lib/postgresql/data"
    networks:
      - docker-compose-crud-network
volumes:
  docker-compose-crud-db-data:
  docker-compose-crud-web-data:
networks:
  docker-compose-crud-network:
